export const founders = [
  {
    name: "Abdel Ali",
    businessName: "Kiwi Charge",
    description:
      "Portable autonomous EV charger for navigating parking lots and charging electric vehicles without human supervision.",
    industryCategory: "Electric Vehicle, IoT, Robotics",
    cohort: "BFN Accelerate",
    sector: "ev",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://www.kiwicharge.ca/",
  },
  {
    name: "Jonathon Bloomfield",
    businessName: "Edventive",
    description:
      "AI tool for teachers to automate administrative tasks like marking and reporting.",
    industryCategory: "Edtech, AI, Education",
    cohort: "BFN Smart Start",
    sector: "education",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://www.edventive.co/",
  },
  {
    name: "Toritse Tuedor",
    businessName: "Tivora Studios",
    description:
      "Tools to help small businesses design, customize, and order on-brand packaging for their products.",
    industryCategory: "Design, Branding, Packaging & Printing",
    cohort: "BFN Accelerate",
    sector: "design",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://tivorastudios.com/",
  },
  {
    name: "Josh Lokko",
    businessName: "Statera",
    description:
      "SaaS platform for simplifying capital markets diligence for public companies and law firms.",
    industryCategory: "SaaS, Financial Services, Legal Tech",
    cohort: "BFN Smart Start",
    sector: "financial",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://www.staterasuite.com/",
  },
  {
    name: "Amina Dan-Sule",
    businessName: "Zakar Photobooth",
    description:
      "Photobooth business model focused on bridging societal gaps and enhancing event experiences for corporate clients.",
    industryCategory: "Events, Social Responsibility, Entrepreneurship",
    cohort: "BFN Smart Start",
    sector: "events",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://zakarphotobooth.com/",
  },
  {
    name: "Tomiwa Olasoko",
    businessName: "Braid-EZ",
    description:
      "Hardware solution for faster and easier African hair braiding for professionals and individuals.",
    industryCategory: "Beauty Tech, Haircare, Innovation",
    cohort: "BFN Smart Start",
    sector: "beauty",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://www.linkedin.com/company/braid-ez/",
  },
  {
    name: "Olayemi Biaou",
    businessName: "Braid-EZ",
    description:
      "Hardware solution for faster and easier African hair braiding for professionals and individuals.",
    industryCategory: "Beauty Tech, Haircare, Innovation",
    cohort: "BFN Smart Start",
    sector: "beauty",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://www.linkedin.com/company/braid-ez/",
  },
  {
    name: "Honma Amadi",
    businessName: "Okeayo",
    description:
      "Unisex clothing brand embedding sustainability into its production processes to ensure affordable, eco-friendly fashion.",
    industryCategory: "Fashion, Sustainability, Retail",
    cohort: "BFN Smart Start",
    sector: "fashion",
    imageUrl: "https://via.placeholder.com/150",
    url: "#",
  },
  {
    name: "Cecil Chikezie",
    businessName: "Global Innovation Design Workshop",
    description:
      "Virtual training programs to address the shortage of biomedical engineering technicians in low-resource areas.",
    industryCategory: "Healthcare, Education, Biomedical Engineering",
    cohort: "BFN Smart Start",
    sector: "healthcare",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://www.linkedin.com/company/gidworkshop/about/",
  },
  {
    name: "Toluwanimi Alebiosu",
    businessName: "Wamiri",
    description:
      "AI-powered data utilization infrastructure for enabling data-driven decision-making for organizations in Africa.",
    industryCategory: "Data Infrastructure, AI, Technology",
    cohort: "BFN Smart Start",
    sector: "data",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://www.linkedin.com/company/wamiri/",
  },
  {
    name: "Isdora Msigwa",
    businessName: "Nuru Health",
    description:
      "Digital platform providing mental health support and wellness resources for Black communities.",
    industryCategory: "Mental Health, Wellness, Community Care",
    cohort: "BFN Smart Start",
    sector: "mentalHealth",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://nuruhealth.my.canva.site/",
  },
  {
    name: "Michael Owusu",
    businessName: "Willify",
    description:
      "Simplified will-drafting platform for diverse demographics in Canada, addressing early will creation.",
    industryCategory: "Legal Tech, Estate Planning, Financial Services",
    cohort: "BFN Smart Start",
    sector: "legalTech",
    imageUrl: "https://via.placeholder.com/150",
    url: "",
  },
  {
    name: "Moses Odemuyiwa",
    businessName: "InfraFlo",
    description:
      "Scalable platform for automating compliance and streamlining operations for transportation and service SMEs.",
    industryCategory: "Logistics, Automation, Field Service Management",
    cohort: "BFN Smart Start",
    sector: "logistics",
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    name: "Chubi Shaibu",
    businessName: "Medidon’tcry",
    description:
      "A hub revitalizing the African design industry by fostering collaboration and innovation in a global market.",
    industryCategory: "Design, Infrastructure, Creative Industry",
    cohort: "BFN Smart Start",
    sector: "design",
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    name: "Igbagbo Ajagunna",
    businessName: "CompCrafter",
    description:
      "HR Tech platform for personalizing and maximizing employee compensation benefits to improve satisfaction.",
    industryCategory: "HR Tech, Employee Benefits, Compensation Management",
    cohort: "BFN Smart Start",
    sector: "hrTech",
    imageUrl: "https://via.placeholder.com/150",
    url: "https://www.linkedin.com/company/compcrafter/",
  },
];
